project:
  type: website

website:
  favicon: "img/memoji_favicon.ico"
  title: "Damon Bayer"
  navbar:
    logo: "img/0018-Damon-Bayer-2048.png"
    # title: false
    right:
      - href: blog.qmd
        text: Blog
  search:
    type: textbox


format:
  html:
    theme: litera
    css: styles.css

resources:
  - CNAME