project:
  type: website

website:
  title: "Damon Bayer, Ph.D."
  navbar:
    right:
      - href: blog.qmd
        text: Blog
      - text: "{{< iconify fa-brands:github-square >}}"
        href: https://github.com/damonbayer
      - text: "{{< iconify fa-brands:linkedin >}}"
        href: https://www.linkedin.com/in/damonbayer/
      - text: "{{< iconify academicons:google-scholar-square >}}"
        href: https://scholar.google.com/citations?user=ewul4B0AAAAJ&hl=en
      - text: "{{< iconify academicons:arxiv-square>}}"
        href: https://arxiv.org/a/bayer_d_1.html
  search:
    type: textbox


format:
  html:
    theme: cosmo
    css: styles.css



