project:
  type: website

website:
  favicon: "img/memoji_favicon.ico"
  title: "Damon Bayer"
  navbar:
    logo: "img/damon_memoji_macbook.png"
    # title: false
    right:
      - href: blog.qmd
        text: Blog
  search:
    type: textbox


format:
  html:
    theme: litera
    css: styles.css



